#' Assign operations using gps and observer or OGT operations diary.
#'
#' Fishing diary can be generated by an observer or by create_diary_from_ogt
#' function.
#' For diaries to work, some columns need to be present:
#' Fecha
#' fec_cal
#' ini_largada
#' fin_largada
#' fec_vir
#' ini_virada
#' fin_virada
#' 
#' These columns will be automatically generated if create_diary_from_ogt is
#' used, so make sure that these columns are present in the file if the diary
#' is created by an observer. On ly dates and times are needed, no positions
#' have to be included on this file.
#'
#' One advantage is that function can process all .csv files under a directory or can do the process for single files.
#' Also a gear for the vessel may be specified if it is known.
#' @param gps_file File where the gps data is.
#' @param diary_file File with the diary info.
#' @param timezone Defaults to UTC.
#' @param use_aggregated Defines if diary data has to be aggregated by gear,
#' This has to be set to TRUE if vessel has used more than one gear in a day,
#' but defaults to FALSE
#' @return returns file a gps one but with fishing operations marked in a new 
#' column named SI_FOPER and values ST (Steaming), SE (Setting), HA (Hauling)
#' and WT (Waiting)  
#' @export
gps_match_oper <- function(gps, diario, timezone = "UTC", use_aggregated = FALSE) {
  # Convert timestamps to POSIXct format
  # gps$DateTime <- as.POSIXct(paste(gps$SI_DATE, gps$SI_TIME), format="%Y-%m-%d %H:%M:%S", tz=timezone)
  
  if (use_aggregated) {
    # Aggregate diario data
    data_to_use <- diario %>%
      group_by(CFR, Fecha, GEAR) %>%
      reframe(
        se_1_dt = min(as.POSIXct(paste(fec_cal, ini_largada), format="%Y-%m-%d %H:%M", tz=timezone)),
        se_2_dt = max(as.POSIXct(paste(fec_cal, fin_largada), format="%Y-%m-%d %H:%M", tz=timezone)),
        ha_1_dt = min(as.POSIXct(paste(fec_vir, ini_virada), format="%Y-%m-%d %H:%M", tz=timezone)),
        ha_2_dt = max(as.POSIXct(paste(fec_vir, fin_virada), format="%Y-%m-%d %H:%M", tz=timezone))
      )
  } else {
    # Use diario as is
    data_to_use <- diario
  }
  
  # Perform the operation
  result <- gps %>%
    left_join(data_to_use, by = c("VE_REF"="CFR", "SI_DATE"="Fecha"), relationship = "many-to-many") %>%
    group_by(VE_REF, SI_DATE, GEAR) %>%
    mutate(
      SI_FOPER = case_when(
        SI_TIMESTAMP < se_1_dt | SI_TIMESTAMP > ha_2_dt ~ "ST",
        SI_TIMESTAMP >= se_1_dt & SI_TIMESTAMP <= se_2_dt ~ "SE",
        SI_TIMESTAMP >= ha_1_dt & SI_TIMESTAMP <= ha_2_dt ~ "HA",
        SI_TIMESTAMP > se_2_dt & SI_TIMESTAMP < ha_1_dt ~ "WT",
        TRUE ~ "UN"
      ),
      SI_FOPER = as.factor(SI_FOPER),
      SI_FSTATUS = if_else(SI_FOPER %in% c("SE", "HA", "WT"), "Y", "N")
    ) %>%
    ungroup()  # Remove grouping
  
  return(result)
}


