#' Assign operations using gps and observer or OGT operations diary.
#'
#' Fishing diary can be generated by an observer,by create_diary_from_ogt
#' function or by captains log.
#' For diaries to work, some columns need to be present:
#' Fecha
#' fec_cal
#' ini_largada
#' fin_largada
#' fec_vir
#' ini_virada
#' fin_virada
#'
#' These columns will be automatically generated if create_diary_from_ogt is
#' used, so make sure that these columns are present in the file if the log file
#' is created by an observer. On ly dates and times are needed, no positions
#' have to be included on this file.
#' @param gps_file File where the gps data is.
#' @param log_file File with the diary info.
#' @param timezone Defaults to UTC.
#' @param log_source Defines where diary data comes from. Options are "obs"
#' for observer, "ogt" for OGTs and "log" for captains log. Defaults to "obs".
#' @return returns a gps file but with fishing operations marked in a new
#' column named SI_FOPER and values ST (Steaming), SE (Setting), HA (Hauling)
#' and WT (Waiting), SI_FSTATUS marked as TRUE or FALSE and the corresponding
#' SU_ISOB, SI_OGT or SI_LOG filled where TRUE.
#' @export
gps_match_oper <- function(gps_file, log_file, timezone = "UTC", log_source = "obs") {

  # Read files based on type (.csv or .RData)
  gps_data <- read_file(gps_file)
  log_data <- read_file(log_file)

  # Convert SI_TIMESTAMP to formato POSIXct and create SI_DATE in gps_data
  gps_data <- gps_data %>%
    mutate(SI_TIMESTAMP = as.POSIXct(SI_TIMESTAMP, format="%Y-%m-%d %H:%M:%S", tz = timezone),
           SI_DATE = as.Date(SI_TIMESTAMP, tz = timezone))


  # Convert log_data columns to POSIXct for prroper combination
  log_data <- log_data %>%
    mutate(
      Fecha = as.Date(Fecha, format="%Y-%m-%d"),  # Convertir Fecha a tipo Date
      ini_largada = as.POSIXct(paste(fec_cal, ini_largada), format="%Y-%m-%d %H:%M", tz=timezone),
      fin_largada = as.POSIXct(paste(fec_cal, fin_largada), format="%Y-%m-%d %H:%M", tz=timezone),
      ini_virada = as.POSIXct(paste(fec_vir, ini_virada), format="%Y-%m-%d %H:%M", tz=timezone),
      fin_virada = as.POSIXct(paste(fec_vir, fin_virada), format="%Y-%m-%d %H:%M", tz=timezone)
    )

  # Join gps_data with log_data using VE_REF and SI_DATE
  combined_data <- gps_data %>%
    left_join(log_data, by = c("VE_REF" = "CFR", "SI_DATE" = "Fecha"))

  # Create SI_FOPER y SI_FSTATUS columns based on conditions
  combined_data <- combined_data %>%
    group_by(VE_REF, FT_REF) %>%
    mutate(
      SI_FOPER = case_when(
        is.na(ini_largada) | is.na(fin_largada) | is.na(ini_virada) | is.na(fin_virada) ~ "UN",  # Sin datos de maniobras
        SI_TIMESTAMP < ini_largada ~ "ST",  # Antes de la largada, navegando
        SI_TIMESTAMP >= ini_largada & SI_TIMESTAMP <= fin_largada ~ "SE",  # Largando aparejos
        SI_TIMESTAMP > fin_largada & SI_TIMESTAMP < ini_virada ~ "WT",  # Esperando
        SI_TIMESTAMP >= ini_virada & SI_TIMESTAMP <= fin_virada ~ "HA",  # Levantando aparejos
        SI_TIMESTAMP > fin_virada ~ "ST",  # Después de la virada, navegando
        TRUE ~ "UN"  # Desconocido si no cumple ninguna condición
      ),
      SI_FSTATUS = if_else(SI_FOPER %in% c("SE", "HA", "WT"), "TRUE", "FALSE")
    ) %>%
    ungroup()  # Remove agrupation

  # Mark proper column based on `log_source` parameter
  combined_data <- combined_data %>%
    mutate(
      SU_ISOB = if_else(log_source == "obs" & !is.na(ini_largada), TRUE, SU_ISOB),
      SI_OGT = if_else(log_source == "ogt" & !is.na(ini_largada), TRUE, SI_OGT),
      SI_LOG = if_else(log_source == "log" & !is.na(ini_largada), TRUE, SI_LOG)
    )

  # Remove unnecessary columns
  combined_data <- combined_data %>% select(-tail(names(.),10))

  # Return final result with updated columns
  return(combined_data)
}

