#' Process GPS data, both white and red
#'
#' This function loads .csv files generated by the  gps and generates .rds
#' files that have an associated geometry column so they can be used as sf
#' objects. The CRS associated with the generated files is epsg:4326.
#' Function will also calculate speed and course over ground (COG) and will
#' remove unnecessary columns.
#'
#' One advantage is that function can process all .csv files under a directory
#' or can do the process for single files.
#' Also a gear for the vessel may be specified if it is known.
#' @param dir Directory where the .csv files are.
#' @param input_file Input file, only needed if process_all is set to FALSE.
#' @param gps_type Type of gps, one of "blanco" or "rojo", defaults to blanco
#' @param vessel_code CFR code of the vessel.
#' @param le_met4_value Metier DCF level 4 if known (optional).
#' @param le_met6_value Metier DCF level 6 if known (optional).
#' @param le_met7_value Target species, AL3 code if known (optional).
#' @param process_all Wheter to process all csv files or not, defaults to FALSE
#' @return A .csv and a RData file with the same base name as the
#' input and _formatted, _formatted_final appended to the file name.
#' @examples
#' # Process only one file
#' process_white_gps_data("/dir/path/to/files/", "filename.csv", gps_type = "blanco", "cfr_code", "3_letter_met4_code", "metier_6_code", "Target_species_AL3")
#' # Process all files in dir
#' process_white_gps_data("/dir/path/to/files/", gps_type = "rojo", "cfr_code", "3_letter_met4_code", proces_all = TRUE)
#' @export
process_gps_data <- function(dir, input_file = NULL, gps_type = "blanco", vessel_code, le_met4_value = NA, le_met6_value = NA, le_met7_value = NA, process_all = FALSE) {

  # Helper function to transform GPS rojo data to the same format as GPS blanco
  transform_red_to_white <- function(file_path) {
    # Load the input CSV file
    data <- readr::read_csv(file_path)

    # Renaming columns to match the gps_blanco structure if they exist
    if ("UTC DATE" %in% colnames(data)) {
      data <- data %>% dplyr::rename(Date = `UTC DATE`)
    }
    if ("UTC TIME" %in% colnames(data)) {
      data <- data %>% dplyr::rename(Time = `UTC TIME`)
    }
    if ("LATITUDE" %in% colnames(data)) {
      data <- data %>% dplyr::rename(Latitude = LATITUDE)
    }
    if ("LONGITUDE" %in% colnames(data)) {
      data <- data %>% dplyr::rename(Longitude = LONGITUDE)
    }
    if ("SPEED" %in% colnames(data)) {
      data <- data %>% dplyr::rename(Speed = SPEED)
    }
    if ("HEADING" %in% colnames(data)) {
      data <- data %>% dplyr::rename(Course = HEADING)
    }
    if ("ALTITUDE" %in% colnames(data)) {
      data <- data %>% dplyr::rename(Altitude = ALTITUDE)
    }

    # Convert Date to Date type and Time to POSIXct type if they exist
    if ("Date" %in% colnames(data)) {
      data <- data %>% dplyr::mutate(Date = as.Date(Date, format = "%Y/%m/%d"))
    }
    if ("Time" %in% colnames(data)) {
      data <- data %>% dplyr::mutate(Time = format(as.POSIXct(Time, format = "%H:%M:%S"), "%H:%M:%S"))
    }

    # Convert speed from m/s to km/h if necessary
    if ("Speed" %in% colnames(data)) {
      data <- data %>% dplyr::mutate(Speed = Speed * 3.6)
    }

    # Add default columns if they do not exist
    if (!"Type" %in% colnames(data)) {
      data <- data %>% dplyr::mutate(Type = 1)
    }
    if (!"Distance" %in% colnames(data)) {
      data <- data %>% dplyr::mutate(Distance = 1)
    }
    if (!"Essential" %in% colnames(data)) {
      data <- data %>% dplyr::mutate(Essential = 1)
    }

    # Remove unnecessary columns and select relevant ones
    data <- data %>% dplyr::select(Date, Time, Latitude, Longitude, Altitude, Speed, Course, Type, Distance, Essential)

    return(data)
  }

  # Process files based on the process_all flag
  if (process_all) {
    files <- list.files(dir, pattern = "\\.csv$", full.names = TRUE)
    for (file_path in files) {
      if (gps_type == "rojo") {
        # Transform the red GPS data to match the white GPS structure
        transformed_data <- transform_red_to_white(file_path)

        # Create a temporary file in the same directory but with a different suffix
        transformed_file_path <- file.path(dir, paste0(tools::file_path_sans_ext(basename(file_path)), "_transformed.csv"))
        write.table(transformed_data, file = transformed_file_path, sep = ";", dec = ".", row.names = FALSE, col.names = TRUE, quote = FALSE)

        # Use the transformed file for process_white_gps_data
        process_white_gps_data(dir, basename(transformed_file_path), vessel_code, le_met4_value, le_met6_value, le_met7_value)

        # Remove the temporary file after processing
        unlink(transformed_file_path)
      } else {
        process_white_gps_data(dir, basename(file_path), vessel_code, le_met4_value, le_met6_value, le_met7_value)
      }
    }
  } else {
    if (is.null(input_file)) {
      stop("input_file must be provided if process_all is FALSE")
    }
    input_path <- file.path(dir, input_file)
    if (gps_type == "rojo") {
      # Transform the red GPS data to match the white GPS structure
      transformed_data <- transform_red_to_white(input_path)

      # Create a temporary file in the same directory but with a different suffix
      transformed_file_path <- file.path(dir, paste0(tools::file_path_sans_ext(basename(input_file)), "_transformed.csv"))
      write.table(transformed_data, file = transformed_file_path, sep = ";", dec = ".", row.names = FALSE, col.names = TRUE, quote = FALSE)

      # Use the transformed file for process_white_gps_data
      process_white_gps_data(dir, basename(transformed_file_path), vessel_code, le_met4_value, le_met6_value, le_met7_value)

      # Remove the temporary file after processing
      unlink(transformed_file_path)
    } else {
      process_white_gps_data(dir, basename(input_path), vessel_code, le_met4_value, le_met6_value, le_met7_value)
    }
  }
}
