#' Process GPS data, both white and red
#'
#' This function loads .csv files generated by the  gps and generates .rds
#' files that have an associated geometry column so they can be used as sf 
#' objects. The CRS associated with the generated files is epsg:4326.
#' Function will also calculate speed and course over ground (COG) and will 
#' remove unnecessary columns.
#'
#' One advantage is that function can process all .csv files under a directory 
#' or can do the process for single files.
#' Also a gear for the vessel may be specified if it is known.
#' @param dir Directory where the .csv files are.
#' @param input_file Input file, only needed if process_all is set to FALSE.
#' @param gps_type Type of gps, one of "blanco" or "rojo", defaults to blanco
#' @param vessel_code CFR code of the vessel.
#' @param le_met4_value Metier DCF level 4 if known (optional).
#' @param le_met6_value Metier DCF level 6 if known (optional).
#' @param le_met7_value Target species, AL3 code if known (optional).
#' @param process_all Wheter to process all csv files or not, defaults to FALSE
#' @return Several procesed .rds and .csv files with the same base name as the 
#' input and _formatted, _formatted_final and formatted_postgis appended to the 
#' file name. Except for the one with the _postgis append, files are created 
#' both in .rds and .csv format. File _final and _postgis have a geometry column,
#' _postgis file geometry is compatible with postgis server.
#' @examples
#' # Process only one file
#' process_white_gps_data("/dir/path/to/files/", "filename.csv", gps_type = "blanco", "cfr_code", "3_letter_met4_code", "metier_6_code", "Target_species_AL3")
#' # Process all files in dir
#' process_white_gps_data("/dir/path/to/files/", gps_type = "rojo", "cfr_code", "3_letter_met4_code", proces_all = TRUE)
#' @export
process_gps_data <- function(dir, input_file = NULL, gps_type = "blanco", vessel_code, le_met4_value = NA, le_met6_value = NA, le_met7_value = NA, process_all = FALSE) {
  
  # Helper function to generate output filenames with correct suffixes
  generate_output_filename <- function(file_path, suffix) {
    base_name <- tools::file_path_sans_ext(basename(file_path))  # Extract the base filename without extension
    return(file.path(dirname(file_path), paste0(base_name, suffix)))  # Append the suffix to the base name
  }
  
  # Helper function to copy the original file with "_orig" appended before the extension
  copy_original_file <- function(file_path) {
    base_name <- tools::file_path_sans_ext(basename(file_path))  # Extract base filename without extension
    new_file_path <- file.path(dirname(file_path), paste0(base_name, "_orig.csv"))  # Append "_orig" before extension
    file.copy(file_path, new_file_path, overwrite = TRUE)  # Copy the original file
    return(new_file_path)  # Return the path of the copied file
  }
  
  # Helper function to transform GPS rojo data to the same format as GPS blanco
  transform_red_to_white <- function(file_path) {
    # Load the input CSV file
    data <- readr::read_csv(file_path)
    
    # Renaming columns to match the gps_blanco structure
    data <- data %>%
      dplyr::rename(
        Date = `UTC DATE`, 
        Time = `UTC TIME`,
        Latitude = LATITUDE, 
        Longitude = LONGITUDE,
        Speed = SPEED, 
        Course = HEADING,
        Altitude = ALTITUDE
      )
    # Convert Date to Date type and Time to POSIXct type
    data <- data %>%
      dplyr::mutate(
        Date = as.Date(Date, format = "%Y/%m/%d"),  # Ensure Date is a valid Date
        Time = format(as.POSIXct(Time, format = "%H:%M:%S"), "%H:%M:%S")  # Ensure Time is a valid time format
      )
    
    # Convert speed from m/s to km/h if necessary
    data <- data %>%
      dplyr::mutate(Speed = Speed * 3.6,
                    Type = 1,
                    Distance = 1,
                    Essential = 1)
    
    # Remove unnecessary columns and select relevant ones
    data <- data %>%
      dplyr::select(Date, Time, Latitude, Longitude, Altitude, Speed, Course, Type, Distance, Essential)

        # Save the transformed file as a new CSV
   # transformed_file_path <- file.path(dirname(file_path), paste0("transformed_", basename(file_path)))
  #  write.table(data, file = transformed_file_path, sep = ";", dec = ".", row.names = FALSE, col.names = TRUE, quote = FALSE)
    
    # Generate the output file path with the "_formatted" suffix
    output_file_path <- generate_output_filename(file_path, ".csv")
    write.table(data, file = output_file_path, sep = ";", dec = ".", row.names = FALSE, col.names = TRUE, quote = FALSE)
    
    
    
    return(output_file_path)
  }
  
  # Process files based on the process_all flag
  if (process_all) {
    files <- list.files(dir, pattern = "\\.csv$", full.names = TRUE)
    for (file_path in files) {
      if (gps_type == "rojo") {
        original_copy <- copy_original_file(file_path)  # Make a copy of the original file with "_orig" before the extension
        transformed_file <- transform_red_to_white(file_path)
        process_white_gps_data(dir, basename(transformed_file), vessel_code, le_met4_value, le_met6_value, le_met7_value)
      } else {
        process_white_gps_data(dir, basename(file_path), vessel_code, le_met4_value, le_met6_value, le_met7_value)
      }
    }
  } else {
    if (is.null(input_file)) {
      stop("input_file must be provided if process_all is FALSE")
    }
    input_path <- file.path(dir, input_file)
    if (gps_type == "rojo") {
      original_copy <- copy_original_file(input_path)  # Make a copy of the original file with "_orig" before the extension
      transformed_file <- transform_red_to_white(input_path)
      process_white_gps_data(dir, basename(transformed_file), vessel_code, le_met4_value, le_met6_value, le_met7_value)
    } else {
      process_white_gps_data(dir, basename(input_path), vessel_code, le_met4_value, le_met6_value, le_met7_value)
    }
  }
}
